-- Fadetouched. Generated from palette.json. Do not edit by hand.
-- Install: add this repo's ports/neovim to runtimepath, then
--   :colorscheme fadetouched

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "fadetouched"

local c = {
  n0 = "#03100f",
  n1 = "#091816",
  n2 = "#11201e",
  n3 = "#1f2d29",
  n4 = "#2e3a36",
  n5 = "#3e4945",
  n6 = "#505a56",
  n7 = "#666f6b",
  n8 = "#7e8580",
  n9 = "#979d98",
  n10 = "#b3b7b4",
  n11 = "#dee1df",
  red = "#c87a75",
  rust = "#bc836c",
  orange = "#d7a176",
  yellow = "#d7be86",
  green = "#96bb93",
  teal = "#81b8a8",
  cyan = "#99c9c9",
  blue = "#7daacf",
  indigo = "#7d89bb",
  purple = "#af90c3",
  magenta = "#c593af",
  pink = "#dbb5c1",
}

vim.g.terminal_color_0 = c.n4
vim.g.terminal_color_1 = c.red
vim.g.terminal_color_2 = c.green
vim.g.terminal_color_3 = c.yellow
vim.g.terminal_color_4 = c.blue
vim.g.terminal_color_5 = c.magenta
vim.g.terminal_color_6 = c.teal
vim.g.terminal_color_7 = c.n9
vim.g.terminal_color_8 = c.n5
vim.g.terminal_color_9 = c.red
vim.g.terminal_color_10 = c.green
vim.g.terminal_color_11 = c.yellow
vim.g.terminal_color_12 = c.blue
vim.g.terminal_color_13 = c.magenta
vim.g.terminal_color_14 = c.teal
vim.g.terminal_color_15 = c.n10

local groups = {
  ["Normal"] = { fg = c.n11, bg = c.n2 },
  ["NormalFloat"] = { fg = c.n11, bg = c.n3 },
  ["FloatBorder"] = { fg = c.n5, bg = c.n3 },
  ["FloatTitle"] = { fg = c.yellow, bg = c.n3, bold = true },
  ["ColorColumn"] = { bg = c.n3 },
  ["Cursor"] = { fg = c.n2, bg = c.pink },
  ["CursorLine"] = { bg = c.n3 },
  ["CursorLineNr"] = { fg = c.indigo, bold = true },
  ["LineNr"] = { fg = c.n7 },
  ["SignColumn"] = { bg = c.n2 },
  ["VertSplit"] = { fg = c.n5 },
  ["WinSeparator"] = { fg = c.n5 },
  ["Folded"] = { fg = c.n9, bg = c.n3 },
  ["FoldColumn"] = { fg = c.n7 },
  ["MatchParen"] = { fg = c.cyan, bg = c.n5 },
  ["NonText"] = { fg = c.n5 },
  ["Whitespace"] = { fg = c.n5 },
  ["Visual"] = { bg = c.n5 },
  ["Search"] = { fg = c.n2, bg = c.yellow },
  ["IncSearch"] = { fg = c.n2, bg = c.orange },
  ["CurSearch"] = { fg = c.n2, bg = c.orange },
  ["Pmenu"] = { fg = c.n11, bg = c.n3 },
  ["PmenuSel"] = { fg = c.n11, bg = c.n5 },
  ["PmenuSbar"] = { bg = c.n3 },
  ["PmenuThumb"] = { bg = c.n6 },
  ["StatusLine"] = { fg = c.n9, bg = c.n1 },
  ["StatusLineNC"] = { fg = c.n7, bg = c.n1 },
  ["TabLine"] = { fg = c.n7, bg = c.n1 },
  ["TabLineSel"] = { fg = c.n11, bg = c.n2 },
  ["TabLineFill"] = { bg = c.n1 },
  ["Title"] = { fg = c.yellow, bold = true },
  ["Directory"] = { fg = c.blue },
  ["ErrorMsg"] = { fg = c.red },
  ["WarningMsg"] = { fg = c.yellow },
  ["MoreMsg"] = { fg = c.green },
  ["ModeMsg"] = { fg = c.n9 },
  ["Question"] = { fg = c.green },
  ["SpecialKey"] = { fg = c.n5 },
  ["Conceal"] = { fg = c.n7 },
  ["WinBar"] = { fg = c.n9, bg = c.n2 },
  ["WinBarNC"] = { fg = c.n7, bg = c.n2 },
  ["Comment"] = { fg = c.n7, italic = true },
  ["Constant"] = { fg = c.orange },
  ["String"] = { fg = c.green },
  ["Character"] = { fg = c.green },
  ["Number"] = { fg = c.orange },
  ["Boolean"] = { fg = c.orange },
  ["Float"] = { fg = c.orange },
  ["Identifier"] = { fg = c.n11 },
  ["Function"] = { fg = c.blue },
  ["Statement"] = { fg = c.purple },
  ["Conditional"] = { fg = c.purple },
  ["Repeat"] = { fg = c.purple },
  ["Label"] = { fg = c.indigo },
  ["Operator"] = { fg = c.cyan },
  ["Keyword"] = { fg = c.purple },
  ["Exception"] = { fg = c.purple },
  ["PreProc"] = { fg = c.indigo },
  ["Include"] = { fg = c.purple },
  ["Define"] = { fg = c.purple },
  ["Macro"] = { fg = c.indigo },
  ["PreCondit"] = { fg = c.indigo },
  ["Type"] = { fg = c.yellow },
  ["StorageClass"] = { fg = c.purple },
  ["Structure"] = { fg = c.yellow },
  ["Typedef"] = { fg = c.yellow },
  ["Special"] = { fg = c.red },
  ["SpecialChar"] = { fg = c.magenta },
  ["Tag"] = { fg = c.teal },
  ["Delimiter"] = { fg = c.n9 },
  ["SpecialComment"] = { fg = c.n8 },
  ["Debug"] = { fg = c.red },
  ["Underlined"] = { fg = c.blue, underline = true },
  ["Error"] = { fg = c.red },
  ["Todo"] = { fg = c.n2, bg = c.yellow, bold = true },
  ["DiagnosticError"] = { fg = c.red },
  ["DiagnosticWarn"] = { fg = c.yellow },
  ["DiagnosticInfo"] = { fg = c.teal },
  ["DiagnosticHint"] = { fg = c.cyan },
  ["DiagnosticUnderlineError"] = { sp = c.red, undercurl = true },
  ["DiagnosticUnderlineWarn"] = { sp = c.yellow, undercurl = true },
  ["DiagnosticUnderlineInfo"] = { sp = c.teal, undercurl = true },
  ["DiagnosticUnderlineHint"] = { sp = c.cyan, undercurl = true },
  ["DiffAdd"] = { fg = c.green, bg = c.n3 },
  ["DiffChange"] = { fg = c.blue, bg = c.n3 },
  ["DiffDelete"] = { fg = c.red, bg = c.n3 },
  ["DiffText"] = { fg = c.n2, bg = c.blue },
  ["Added"] = { fg = c.green },
  ["Changed"] = { fg = c.blue },
  ["Removed"] = { fg = c.red },
  ["GitSignsAdd"] = { fg = c.green },
  ["GitSignsChange"] = { fg = c.blue },
  ["GitSignsDelete"] = { fg = c.red },
  ["@comment"] = { link = "Comment" },
  ["@keyword"] = { fg = c.purple },
  ["@keyword.function"] = { fg = c.purple },
  ["@keyword.return"] = { fg = c.purple },
  ["@keyword.operator"] = { fg = c.purple },
  ["@keyword.import"] = { fg = c.purple },
  ["@keyword.conditional"] = { fg = c.purple },
  ["@keyword.repeat"] = { fg = c.purple },
  ["@keyword.exception"] = { fg = c.purple },
  ["@string"] = { fg = c.green },
  ["@string.escape"] = { fg = c.magenta },
  ["@string.regexp"] = { fg = c.magenta },
  ["@string.special"] = { fg = c.magenta },
  ["@character"] = { fg = c.green },
  ["@number"] = { fg = c.orange },
  ["@boolean"] = { fg = c.orange },
  ["@number.float"] = { fg = c.orange },
  ["@constant"] = { fg = c.orange },
  ["@constant.builtin"] = { fg = c.red },
  ["@constant.macro"] = { fg = c.indigo },
  ["@function"] = { fg = c.blue },
  ["@function.call"] = { fg = c.blue },
  ["@function.builtin"] = { fg = c.red },
  ["@function.macro"] = { fg = c.indigo },
  ["@function.method"] = { fg = c.blue },
  ["@function.method.call"] = { fg = c.blue },
  ["@constructor"] = { fg = c.yellow },
  ["@type"] = { fg = c.yellow },
  ["@type.builtin"] = { fg = c.yellow },
  ["@type.definition"] = { fg = c.yellow },
  ["@variable"] = { fg = c.n11 },
  ["@variable.builtin"] = { fg = c.red },
  ["@variable.parameter"] = { fg = c.rust },
  ["@variable.member"] = { fg = c.blue },
  ["@property"] = { fg = c.blue },
  ["@field"] = { fg = c.blue },
  ["@namespace"] = { fg = c.yellow },
  ["@module"] = { fg = c.yellow },
  ["@operator"] = { fg = c.cyan },
  ["@punctuation.delimiter"] = { fg = c.n9 },
  ["@punctuation.bracket"] = { fg = c.n9 },
  ["@punctuation.special"] = { fg = c.cyan },
  ["@tag"] = { fg = c.teal },
  ["@tag.attribute"] = { fg = c.yellow },
  ["@tag.delimiter"] = { fg = c.n9 },
  ["@attribute"] = { fg = c.indigo },
  ["@label"] = { fg = c.indigo },
  ["@markup.heading"] = { fg = c.yellow, bold = true },
  ["@markup.strong"] = { fg = c.orange, bold = true },
  ["@markup.italic"] = { fg = c.blue, italic = true },
  ["@markup.link"] = { fg = c.teal },
  ["@markup.link.url"] = { fg = c.blue, underline = true },
  ["@markup.raw"] = { fg = c.green },
  ["@markup.list"] = { fg = c.cyan },
  ["@diff.plus"] = { fg = c.green },
  ["@diff.minus"] = { fg = c.red },
  ["@diff.delta"] = { fg = c.blue },
  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.decorator"] = { link = "@function.macro" },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.enumMember"] = { fg = c.orange },
  ["@lsp.type.function"] = { link = "@function" },
  ["@lsp.type.interface"] = { link = "@type" },
  ["@lsp.type.macro"] = { link = "@function.macro" },
  ["@lsp.type.method"] = { link = "@function.method" },
  ["@lsp.type.namespace"] = { link = "@namespace" },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.variable"] = { link = "@variable" },
  ["@lsp.type.keyword"] = { link = "@keyword" },
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end
