export const label = "Neovim";

export default function render(ctx) {
  const { meta, raw } = ctx;

  const groups = [
    ["Normal", { fg: "n11", bg: "n2" }],
    ["NormalFloat", { fg: "n11", bg: "n3" }],
    ["FloatBorder", { fg: "n5", bg: "n3" }],
    ["FloatTitle", { fg: "yellow", bg: "n3", bold: true }],
    ["ColorColumn", { bg: "n3" }],
    ["Cursor", { fg: "n2", bg: "pink" }],
    ["CursorLine", { bg: "n3" }],
    ["CursorLineNr", { fg: "indigo", bold: true }],
    ["LineNr", { fg: "n7" }],
    ["SignColumn", { bg: "n2" }],
    ["VertSplit", { fg: "n5" }],
    ["WinSeparator", { fg: "n5" }],
    ["Folded", { fg: "n9", bg: "n3" }],
    ["FoldColumn", { fg: "n7" }],
    ["MatchParen", { fg: "cyan", bg: "n5" }],
    ["NonText", { fg: "n5" }],
    ["Whitespace", { fg: "n5" }],
    ["Visual", { bg: "n5" }],
    ["Search", { fg: "n2", bg: "yellow" }],
    ["IncSearch", { fg: "n2", bg: "orange" }],
    ["CurSearch", { fg: "n2", bg: "orange" }],
    ["Pmenu", { fg: "n11", bg: "n3" }],
    ["PmenuSel", { fg: "n11", bg: "n5" }],
    ["PmenuSbar", { bg: "n3" }],
    ["PmenuThumb", { bg: "n6" }],
    ["StatusLine", { fg: "n9", bg: "n1" }],
    ["StatusLineNC", { fg: "n7", bg: "n1" }],
    ["TabLine", { fg: "n7", bg: "n1" }],
    ["TabLineSel", { fg: "n11", bg: "n2" }],
    ["TabLineFill", { bg: "n1" }],
    ["Title", { fg: "yellow", bold: true }],
    ["Directory", { fg: "blue" }],
    ["ErrorMsg", { fg: "red" }],
    ["WarningMsg", { fg: "yellow" }],
    ["MoreMsg", { fg: "green" }],
    ["ModeMsg", { fg: "n9" }],
    ["Question", { fg: "green" }],
    ["SpecialKey", { fg: "n5" }],
    ["Conceal", { fg: "n7" }],
    ["WinBar", { fg: "n9", bg: "n2" }],
    ["WinBarNC", { fg: "n7", bg: "n2" }],

    ["Comment", { fg: "n7", italic: true }],
    ["Constant", { fg: "orange" }],
    ["String", { fg: "green" }],
    ["Character", { fg: "green" }],
    ["Number", { fg: "orange" }],
    ["Boolean", { fg: "orange" }],
    ["Float", { fg: "orange" }],
    ["Identifier", { fg: "n11" }],
    ["Function", { fg: "blue" }],
    ["Statement", { fg: "purple" }],
    ["Conditional", { fg: "purple" }],
    ["Repeat", { fg: "purple" }],
    ["Label", { fg: "indigo" }],
    ["Operator", { fg: "cyan" }],
    ["Keyword", { fg: "purple" }],
    ["Exception", { fg: "purple" }],
    ["PreProc", { fg: "indigo" }],
    ["Include", { fg: "purple" }],
    ["Define", { fg: "purple" }],
    ["Macro", { fg: "indigo" }],
    ["PreCondit", { fg: "indigo" }],
    ["Type", { fg: "yellow" }],
    ["StorageClass", { fg: "purple" }],
    ["Structure", { fg: "yellow" }],
    ["Typedef", { fg: "yellow" }],
    ["Special", { fg: "red" }],
    ["SpecialChar", { fg: "magenta" }],
    ["Tag", { fg: "teal" }],
    ["Delimiter", { fg: "n9" }],
    ["SpecialComment", { fg: "n8" }],
    ["Debug", { fg: "red" }],
    ["Underlined", { fg: "blue", underline: true }],
    ["Error", { fg: "red" }],
    ["Todo", { fg: "n2", bg: "yellow", bold: true }],

    ["DiagnosticError", { fg: "red" }],
    ["DiagnosticWarn", { fg: "yellow" }],
    ["DiagnosticInfo", { fg: "teal" }],
    ["DiagnosticHint", { fg: "cyan" }],
    ["DiagnosticUnderlineError", { undercurl: true, sp: "red" }],
    ["DiagnosticUnderlineWarn", { undercurl: true, sp: "yellow" }],
    ["DiagnosticUnderlineInfo", { undercurl: true, sp: "teal" }],
    ["DiagnosticUnderlineHint", { undercurl: true, sp: "cyan" }],

    ["DiffAdd", { fg: "green", bg: "n3" }],
    ["DiffChange", { fg: "blue", bg: "n3" }],
    ["DiffDelete", { fg: "red", bg: "n3" }],
    ["DiffText", { fg: "n2", bg: "blue" }],
    ["Added", { fg: "green" }],
    ["Changed", { fg: "blue" }],
    ["Removed", { fg: "red" }],
    ["GitSignsAdd", { fg: "green" }],
    ["GitSignsChange", { fg: "blue" }],
    ["GitSignsDelete", { fg: "red" }],

    ["@comment", { link: "Comment" }],
    ["@keyword", { fg: "purple" }],
    ["@keyword.function", { fg: "purple" }],
    ["@keyword.return", { fg: "purple" }],
    ["@keyword.operator", { fg: "purple" }],
    ["@keyword.import", { fg: "purple" }],
    ["@keyword.conditional", { fg: "purple" }],
    ["@keyword.repeat", { fg: "purple" }],
    ["@keyword.exception", { fg: "purple" }],
    ["@string", { fg: "green" }],
    ["@string.escape", { fg: "magenta" }],
    ["@string.regexp", { fg: "magenta" }],
    ["@string.special", { fg: "magenta" }],
    ["@character", { fg: "green" }],
    ["@number", { fg: "orange" }],
    ["@boolean", { fg: "orange" }],
    ["@number.float", { fg: "orange" }],
    ["@constant", { fg: "orange" }],
    ["@constant.builtin", { fg: "red" }],
    ["@constant.macro", { fg: "indigo" }],
    ["@function", { fg: "blue" }],
    ["@function.call", { fg: "blue" }],
    ["@function.builtin", { fg: "red" }],
    ["@function.macro", { fg: "indigo" }],
    ["@function.method", { fg: "blue" }],
    ["@function.method.call", { fg: "blue" }],
    ["@constructor", { fg: "yellow" }],
    ["@type", { fg: "yellow" }],
    ["@type.builtin", { fg: "yellow" }],
    ["@type.definition", { fg: "yellow" }],
    ["@variable", { fg: "n11" }],
    ["@variable.builtin", { fg: "red" }],
    ["@variable.parameter", { fg: "rust" }],
    ["@variable.member", { fg: "blue" }],
    ["@property", { fg: "blue" }],
    ["@field", { fg: "blue" }],
    ["@namespace", { fg: "yellow" }],
    ["@module", { fg: "yellow" }],
    ["@operator", { fg: "cyan" }],
    ["@punctuation.delimiter", { fg: "n9" }],
    ["@punctuation.bracket", { fg: "n9" }],
    ["@punctuation.special", { fg: "cyan" }],
    ["@tag", { fg: "teal" }],
    ["@tag.attribute", { fg: "yellow" }],
    ["@tag.delimiter", { fg: "n9" }],
    ["@attribute", { fg: "indigo" }],
    ["@label", { fg: "indigo" }],
    ["@markup.heading", { fg: "yellow", bold: true }],
    ["@markup.strong", { fg: "orange", bold: true }],
    ["@markup.italic", { fg: "blue", italic: true }],
    ["@markup.link", { fg: "teal" }],
    ["@markup.link.url", { fg: "blue", underline: true }],
    ["@markup.raw", { fg: "green" }],
    ["@markup.list", { fg: "cyan" }],
    ["@diff.plus", { fg: "green" }],
    ["@diff.minus", { fg: "red" }],
    ["@diff.delta", { fg: "blue" }],

    ["@lsp.type.class", { link: "@type" }],
    ["@lsp.type.decorator", { link: "@function.macro" }],
    ["@lsp.type.enum", { link: "@type" }],
    ["@lsp.type.enumMember", { fg: "orange" }],
    ["@lsp.type.function", { link: "@function" }],
    ["@lsp.type.interface", { link: "@type" }],
    ["@lsp.type.macro", { link: "@function.macro" }],
    ["@lsp.type.method", { link: "@function.method" }],
    ["@lsp.type.namespace", { link: "@namespace" }],
    ["@lsp.type.parameter", { link: "@variable.parameter" }],
    ["@lsp.type.property", { link: "@property" }],
    ["@lsp.type.struct", { link: "@type" }],
    ["@lsp.type.type", { link: "@type" }],
    ["@lsp.type.variable", { link: "@variable" }],
    ["@lsp.type.keyword", { link: "@keyword" }],
  ];

  const spec = (s) => {
    if (s.link) return `{ link = "${s.link}" }`;
    const parts = [];
    if (s.fg) parts.push(`fg = c.${s.fg}`);
    if (s.bg) parts.push(`bg = c.${s.bg}`);
    if (s.sp) parts.push(`sp = c.${s.sp}`);
    for (const flag of ["bold", "italic", "underline", "undercurl"]) {
      if (s[flag]) parts.push(`${flag} = true`);
    }
    return `{ ${parts.join(", ")} }`;
  };

  const paletteLines = [
    ...Object.entries(raw.neutrals),
    ...Object.entries(raw.accents),
  ].map(([k, v]) => `  ${k} = "${v}",`);

  const groupLines = groups.map(([name, s]) => `  ["${name}"] = ${spec(s)},`);

  const ansiKeys = [
    "n4", "red", "green", "yellow", "blue", "magenta", "teal", "n9",
    "n5", "red", "green", "yellow", "blue", "magenta", "teal", "n10",
  ];
  const termLines = ansiKeys.map((k, i) => `vim.g.terminal_color_${i} = c.${k}`);

  const out = [
    `-- ${meta.name}. Generated from palette.json. Do not edit by hand.`,
    `-- Install: add this repo's ports/neovim to runtimepath, then`,
    `--   :colorscheme fadetouched`,
    ``,
    `vim.cmd("highlight clear")`,
    `if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end`,
    `vim.o.background = "${meta.appearance}"`,
    `vim.g.colors_name = "fadetouched"`,
    ``,
    `local c = {`,
    ...paletteLines,
    `}`,
    ``,
    ...termLines,
    ``,
    `local groups = {`,
    ...groupLines,
    `}`,
    ``,
    `for group, opts in pairs(groups) do`,
    `  vim.api.nvim_set_hl(0, group, opts)`,
    `end`,
    ``,
  ].join("\n");

  return [{ path: "ports/neovim/colors/fadetouched.lua", content: out }];
}
