export const label = "Nushell";

export default function render(ctx) {
  const { meta, accent, sem, syn } = ctx;

  const s = {
    text: sem.text,
    bg: sem.bg,
    faint: sem["text-faint"],
    border: sem["border-strong"],
    surfaceActive: sem["surface-active"],
    command: syn.function,
    string: syn.string,
    constant: syn.number,
    operator: syn.operator,
    filepath: accent.blue,
    keyword: syn.keyword,
    punct: syn.punctuation,
    error: sem.error,
    flag: syn.parameter,
    variable: accent.rust,
    custom: accent.pink,
    match: accent.green,
    teal: accent.teal,
    interp: syn.escape,
    datetime: accent.purple,
    search: accent.yellow,
    cursor: sem.cursor,
  };

  const body = [
    `    separator: "${s.border}"`,
    `    leading_trailing_space_bg: { bg: "${s.surfaceActive}" }`,
    `    header: { fg: "${s.text}" attr: b }`,
    `    row_index: { fg: "${s.faint}" }`,
    `    record: "${s.text}"`,
    `    list: "${s.text}"`,
    `    hints: "${s.faint}"`,
    `    empty: "${s.command}"`,
    `    search_result: { fg: "${s.bg}" bg: "${s.search}" }`,
    `    bool: "${s.constant}"`,
    `    int: "${s.constant}"`,
    `    float: "${s.constant}"`,
    `    string: "${s.string}"`,
    `    nothing: "${s.constant}"`,
    `    binary: "${s.constant}"`,
    `    "cell-path": "${s.punct}"`,
    `    datetime: "${s.datetime}"`,
    `    filesize: "${s.teal}"`,
    `    duration: "${s.teal}"`,
    `    range: "${s.operator}"`,
    `    glob: "${s.filepath}"`,
    `    background: "${s.bg}"`,
    `    foreground: "${s.text}"`,
    `    cursor: { fg: "${s.bg}" bg: "${s.cursor}" }`,
    `    shape_binary: "${s.constant}"`,
    `    shape_bool: "${s.constant}"`,
    `    shape_int: "${s.constant}"`,
    `    shape_float: "${s.constant}"`,
    `    shape_nothing: "${s.constant}"`,
    `    shape_datetime: "${s.constant}"`,
    `    shape_range: "${s.operator}"`,
    `    shape_operator: "${s.operator}"`,
    `    shape_pipe: { fg: "${s.operator}" attr: b }`,
    `    shape_redirection: { fg: "${s.operator}" attr: b }`,
    `    shape_string: "${s.string}"`,
    `    shape_raw_string: "${s.string}"`,
    `    shape_string_interpolation: "${s.interp}"`,
    `    shape_externalarg: "${s.string}"`,
    `    shape_record: "${s.punct}"`,
    `    shape_list: "${s.punct}"`,
    `    shape_table: "${s.punct}"`,
    `    shape_filepath: "${s.filepath}"`,
    `    shape_directory: "${s.filepath}"`,
    `    shape_globpattern: "${s.filepath}"`,
    `    shape_glob_interpolation: "${s.filepath}"`,
    `    shape_garbage: { fg: "${s.bg}" bg: "${s.error}" attr: b }`,
    `    shape_variable: { fg: "${s.variable}" attr: i }`,
    `    shape_vardecl: { fg: "${s.variable}" attr: i }`,
    `    shape_matching_brackets: { attr: u }`,
    `    shape_internalcall: { fg: "${s.command}" attr: b }`,
    `    shape_external: "${s.command}"`,
    `    shape_external_resolved: { fg: "${s.command}" attr: b }`,
    `    shape_block: { fg: "${s.command}" attr: b }`,
    `    shape_literal: "${s.command}"`,
    `    shape_custom: "${s.custom}"`,
    `    shape_keyword: { fg: "${s.keyword}" attr: b }`,
    `    shape_match_pattern: "${s.match}"`,
    `    shape_signature: "${s.teal}"`,
    `    shape_flag: { fg: "${s.flag}" attr: i }`,
    `    shape_closure: { fg: "${s.teal}" attr: b }`,
  ];

  const lines = [
    `# ${meta.name} for Nushell. Generated from ${meta.source}. Do not edit by hand.`,
    "# Add to config.nu BEFORE `let config = ...`, or run: source /path/to/fadetouched.nu",
    `$env.config.color_config = {`,
    ...body,
    `}`,
    ``,
  ];

  return [{ path: `ports/nushell/${meta.slug}.nu`, content: lines.join("\n") }];
}
