import { alpha } from "../lib/color.mjs";

export const label = "Sublime Text";

export default function render(ctx) {
  const { meta, n, accent, sem, syn } = ctx;
  const rule = (name, scope, foreground, fontStyle) => ({
    name,
    scope,
    foreground,
    ...(fontStyle ? { font_style: fontStyle } : {}),
  });

  const scheme = {
    name: meta.name,
    variables: {
      bg: sem.bg,
      bg_dim: sem["bg-dim"],
      surface: sem.surface,
      surface_hover: sem["surface-hover"],
      border: sem.border,
      border_strong: sem["border-strong"],
      text: sem.text,
      text_muted: sem["text-muted"],
      text_subtle: sem["text-subtle"],
      text_faint: sem["text-faint"],
      accent: sem.accent,
      cursor: sem.cursor,
      error: sem.error,
      warning: sem.warning,
      success: sem.success,
      info: sem.info,
    },
    globals: {
      background: "var(bg)",
      foreground: "var(text)",
      invisibles: "var(border)",
      caret: "var(cursor)",
      block_caret: "var(cursor)",
      block_caret_border: "var(cursor)",
      block_caret_underline: "var(cursor)",
      line_highlight: alpha(sem.text, 5),
      misspelling: "var(error)",
      fold_marker: "var(text_faint)",
      minimap_border: "var(border)",
      accent: "var(accent)",
      gutter: "var(bg_dim)",
      gutter_foreground: "var(text_faint)",
      gutter_foreground_highlight: "var(text_muted)",
      line_diff_added: "var(success)",
      line_diff_modified: "var(warning)",
      line_diff_deleted: "var(error)",
      selection: alpha(sem.accent, 25),
      selection_border: alpha(sem.accent, 50),
      inactive_selection: alpha(sem["border-strong"], 25),
      inactive_selection_border: "var(border)",
      highlight: "var(info)",
      find_highlight: alpha(sem.warning, 35),
      find_highlight_foreground: "var(text)",
      scroll_highlight: "var(info)",
      scroll_selected_highlight: "var(accent)",
      rulers: "var(border)",
      guide: "var(surface)",
      active_guide: "var(border_strong)",
      stack_guide: "var(border)",
      brackets_options: "underline",
      brackets_foreground: "var(info)",
      bracket_contents_options: "underline",
      bracket_contents_foreground: "var(info)",
      tags_options: "underline",
      tags_foreground: "var(accent)",
      shadow: n.n0,
    },
    rules: [
      rule("Comments", "comment, punctuation.definition.comment", syn.comment, "italic"),
      rule("Strings", "string", syn.string),
      rule("Escapes and regular expressions", "constant.character.escape, string.regexp", syn.escape),
      rule("Numbers", "constant.numeric", syn.number),
      rule("Language constants", "constant.language", syn.number),
      rule("Keywords", "keyword, storage.type, storage.modifier", syn.keyword),
      rule("Functions", "entity.name.function, support.function", syn.function),
      rule("Types", "entity.name.type, entity.name.class, support.type, support.class", syn.type),
      rule("Inherited classes", "entity.other.inherited-class", syn.type),
      rule("Tags", "entity.name.tag", syn.tag),
      rule("Attributes", "entity.other.attribute-name", syn.attribute),
      rule("Variables", "variable", sem.text),
      rule("Parameters", "variable.parameter", syn.parameter),
      rule("Language variables", "variable.language, support.variable", syn.builtin),
      rule("Properties", "variable.other.property, support.variable.property", syn.property),
      rule("Operators", "keyword.operator", syn.operator),
      rule("Punctuation", "punctuation", syn.punctuation),
      rule("Decorators", "meta.decorator, entity.name.function.decorator", syn.decorator),
      rule("Headings", "markup.heading, entity.name.section", accent.yellow, "bold"),
      rule("Bold", "markup.bold", accent.orange, "bold"),
      rule("Italic", "markup.italic", accent.blue, "italic"),
      rule("Links", "markup.underline.link, string.other.link", sem.link, "underline"),
      rule("Inserted", "markup.inserted", sem.success),
      rule("Changed", "markup.changed", sem.warning),
      rule("Deleted", "markup.deleted", sem.error),
      rule("Invalid", "invalid", sem.error, "underline"),
    ],
  };

  return [
    {
      path: `ports/sublime-text/${meta.name}.sublime-color-scheme`,
      content: JSON.stringify(scheme, null, 2) + "\n",
    },
  ];
}
