export const label = "Yazi";

const xmlEscape = (value) =>
  value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");

const tmEntry = (name, scope, settings) => {
  const pairs = Object.entries(settings)
    .map(([key, value]) => `      <key>${key}</key>\n      <string>${xmlEscape(value)}</string>`)
    .join("\n");
  return [
    `    <dict>`,
    `      <key>name</key>`,
    `      <string>${xmlEscape(name)}</string>`,
    ...(scope ? [`      <key>scope</key>`, `      <string>${xmlEscape(scope)}</string>`] : []),
    `      <key>settings</key>`,
    `      <dict>`,
    pairs,
    `      </dict>`,
    `    </dict>`,
  ].join("\n");
};

export default function render(ctx) {
  const { meta, n, accent, sem, syn } = ctx;

  const flavor = [
    `[app]`,
    `overall = { fg = "${sem.text}", bg = "${sem.bg}" }`,
    ``,
    `[mgr]`,
    `cwd = { fg = "${accent.teal}" }`,
    `find_keyword = { fg = "${accent.yellow}", bold = true, italic = true, underline = true }`,
    `find_position = { fg = "${accent.magenta}", bg = "reset", bold = true, italic = true }`,
    `symlink_target = { fg = "${sem["text-subtle"]}", italic = true }`,
    `marker_copied = { fg = "${accent.green}", bg = "${accent.green}" }`,
    `marker_cut = { fg = "${accent.red}", bg = "${accent.red}" }`,
    `marker_marked = { fg = "${accent.teal}", bg = "${accent.teal}" }`,
    `marker_selected = { fg = "${accent.yellow}", bg = "${accent.yellow}" }`,
    `count_copied = { fg = "${sem.bg}", bg = "${accent.green}" }`,
    `count_cut = { fg = "${sem.bg}", bg = "${accent.red}" }`,
    `count_selected = { fg = "${sem.bg}", bg = "${accent.yellow}" }`,
    `border_style = { fg = "${sem.border}" }`,
    ``,
    `[tabs]`,
    `active = { fg = "${sem.bg}", bg = "${accent.green}", bold = true }`,
    `inactive = { fg = "${sem["text-muted"]}", bg = "${sem.surface}" }`,
    ``,
    `[mode]`,
    `normal_main = { fg = "${sem.bg}", bg = "${accent.green}", bold = true }`,
    `normal_alt = { fg = "${accent.green}", bg = "${sem.surface}" }`,
    `select_main = { fg = "${sem.bg}", bg = "${accent.teal}", bold = true }`,
    `select_alt = { fg = "${accent.teal}", bg = "${sem.surface}" }`,
    `unset_main = { fg = "${sem.bg}", bg = "${accent.red}", bold = true }`,
    `unset_alt = { fg = "${accent.red}", bg = "${sem.surface}" }`,
    ``,
    `[indicator]`,
    `parent = { fg = "${sem["text-subtle"]}" }`,
    `current = { fg = "${accent.green}", bold = true }`,
    `preview = { fg = "${accent.teal}", underline = true }`,
    ``,
    `[status]`,
    `overall = { fg = "${sem["text-muted"]}", bg = "${sem["bg-dim"]}" }`,
    `perm_sep = { fg = "${sem["text-faint"]}" }`,
    `perm_type = { fg = "${accent.blue}" }`,
    `perm_read = { fg = "${accent.yellow}" }`,
    `perm_write = { fg = "${accent.red}" }`,
    `perm_exec = { fg = "${accent.green}" }`,
    `progress_label = { fg = "${sem.text}", bold = true }`,
    `progress_normal = { fg = "${accent.green}", bg = "${sem.surface}" }`,
    `progress_error = { fg = "${sem.bg}", bg = "${accent.red}" }`,
    ``,
    `[which]`,
    `mask = { bg = "${sem["bg-dim"]}" }`,
    `cand = { fg = "${accent.cyan}" }`,
    `rest = { fg = "${sem["text-subtle"]}" }`,
    `desc = { fg = "${accent.purple}" }`,
    `separator_style = { fg = "${sem.border}" }`,
    ``,
    `[confirm]`,
    `border = { fg = "${accent.green}" }`,
    `title = { fg = "${accent.green}" }`,
    `body = { fg = "${sem.text}" }`,
    `list = { fg = "${sem["text-muted"]}" }`,
    `btn_yes = { fg = "${sem.bg}", bg = "${accent.green}", bold = true }`,
    `btn_no = { fg = "${sem["text-muted"]}" }`,
    ``,
    `[spot]`,
    `border = { fg = "${accent.green}" }`,
    `title = { fg = "${accent.green}" }`,
    `tbl_col = { fg = "${accent.teal}" }`,
    `tbl_cell = { fg = "${sem.text}", bg = "${sem.surface}" }`,
    ``,
    `[notify]`,
    `title_info = { fg = "${accent.teal}" }`,
    `title_warn = { fg = "${accent.yellow}" }`,
    `title_error = { fg = "${accent.red}" }`,
    ``,
    `[pick]`,
    `border = { fg = "${accent.green}" }`,
    `active = { fg = "${accent.purple}", bold = true }`,
    `inactive = { fg = "${sem["text-muted"]}" }`,
    ``,
    `[input]`,
    `border = { fg = "${accent.green}" }`,
    `title = { fg = "${sem.text}" }`,
    `value = { fg = "${sem.text}" }`,
    `selected = { bg = "${sem["surface-active"]}" }`,
    ``,
    `[cmp]`,
    `border = { fg = "${accent.green}" }`,
    `active = { bg = "${sem["surface-active"]}", bold = true }`,
    `inactive = { fg = "${sem["text-muted"]}" }`,
    ``,
    `[tasks]`,
    `border = { fg = "${accent.green}" }`,
    `title = { fg = "${sem.text}" }`,
    `hovered = { fg = "${accent.purple}", bold = true }`,
    ``,
    `[help]`,
    `on = { fg = "${accent.cyan}" }`,
    `run = { fg = "${accent.purple}" }`,
    `desc = { fg = "${sem["text-muted"]}" }`,
    `hovered = { bg = "${sem["surface-active"]}", bold = true }`,
    `footer = { fg = "${sem.bg}", bg = "${sem.text}" }`,
    ``,
    `[filetype]`,
    `rules = [`,
    `  { mime = "image/*", fg = "${accent.teal}" },`,
    `  { mime = "{audio,video}/*", fg = "${accent.yellow}" },`,
    `  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "${accent.magenta}" },`,
    `  { mime = "application/{pdf,doc,rtf}", fg = "${accent.blue}" },`,
    `  { mime = "vfs/{absent,stale}", fg = "${sem["text-subtle"]}" },`,
    `  { url = "*", is = "orphan", fg = "${sem.bg}", bg = "${accent.red}" },`,
    `  { url = "*", is = "exec", fg = "${accent.green}" },`,
    `  { url = "*", fg = "${sem.text}" },`,
    `  { url = "*/", fg = "${accent.blue}" },`,
    `]`,
    ``,
  ].join("\n");

  const entries = [
    tmEntry(meta.name, "", {
      background: sem.bg,
      foreground: sem.text,
      caret: sem.cursor,
      selection: sem["surface-active"],
      lineHighlight: sem.surface,
      invisibles: sem.border,
    }),
    tmEntry("Comments", "comment, punctuation.definition.comment", {
      foreground: syn.comment,
      fontStyle: "italic",
    }),
    tmEntry("Strings", "string", { foreground: syn.string }),
    tmEntry("Escapes", "constant.character.escape, string.regexp", { foreground: syn.escape }),
    tmEntry("Numbers", "constant.numeric, constant.language", { foreground: syn.number }),
    tmEntry("Keywords", "keyword, storage.type, storage.modifier", { foreground: syn.keyword }),
    tmEntry("Functions", "entity.name.function, support.function", { foreground: syn.function }),
    tmEntry("Types", "entity.name.type, entity.name.class, support.type, support.class", {
      foreground: syn.type,
    }),
    tmEntry("Parameters", "variable.parameter", { foreground: syn.parameter }),
    tmEntry("Properties", "variable.other.property, support.variable.property", {
      foreground: syn.property,
    }),
    tmEntry("Tags", "entity.name.tag", { foreground: syn.tag }),
    tmEntry("Attributes", "entity.other.attribute-name", { foreground: syn.attribute }),
    tmEntry("Operators", "keyword.operator", { foreground: syn.operator }),
    tmEntry("Punctuation", "punctuation", { foreground: syn.punctuation }),
    tmEntry("Invalid", "invalid", { foreground: sem.error }),
  ];
  const tmTheme = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`,
    `<plist version="1.0">`,
    `<dict>`,
    `  <key>name</key>`,
    `  <string>${meta.name}</string>`,
    `  <key>settings</key>`,
    `  <array>`,
    entries.join("\n"),
    `  </array>`,
    `</dict>`,
    `</plist>`,
    ``,
  ].join("\n");

  const root = `ports/yazi/${meta.slug}.yazi`;
  return [
    { path: `${root}/flavor.toml`, content: flavor },
    { path: `${root}/tmtheme.xml`, content: tmTheme },
  ];
}
