import { alpha } from "../lib/color.mjs";

export const label = "Zed";

const TRANSPARENT = "#00000000";

export default function render(ctx) {
  const { meta, n, accent, sem, syn, ansi } = ctx;

  const baseStyle = {
    background: sem["bg-dim"],
    "surface.background": sem["bg-dim"],
    "elevated_surface.background": sem.surface,
    "element.background": sem.surface,
    "element.hover": sem["surface-hover"],
    "element.active": sem["surface-active"],
    "element.selected": sem["surface-active"],
    "element.disabled": sem.surface,
    "ghost_element.background": TRANSPARENT,
    "ghost_element.hover": alpha(sem.text, 5),
    "ghost_element.active": sem["surface-active"],
    "ghost_element.selected": sem["surface-active"],
    "ghost_element.disabled": sem.surface,
    border: sem.border,
    "border.variant": sem["surface-hover"],
    "border.focused": accent.indigo,
    "border.selected": alpha(accent.indigo, 60),
    "border.transparent": TRANSPARENT,
    "border.disabled": sem["surface-hover"],
    text: sem.text,
    "text.muted": sem["text-subtle"],
    "text.placeholder": sem["text-faint"],
    "text.disabled": sem["text-faint"],
    "text.accent": sem.link,
    icon: sem["text-subtle"],
    "icon.muted": sem["text-faint"],
    "icon.disabled": sem["text-faint"],
    "icon.placeholder": sem["text-subtle"],
    "icon.accent": sem.link,
    "title_bar.background": sem["bg-dim"],
    "title_bar.inactive_background": sem["bg-sunken"],
    "status_bar.background": sem["bg-dim"],
    "toolbar.background": sem.bg,
    "tab_bar.background": sem["bg-dim"],
    "tab.inactive_background": sem["bg-dim"],
    "tab.active_background": sem.bg,
    "panel.background": sem["bg-dim"],
    "drop_target.background": alpha(sem["text-subtle"], 25),
    "scrollbar.thumb.background": alpha(sem["border-strong"], 50),
    "scrollbar.thumb.hover_background": alpha(sem["border-strong"], 70),
    "scrollbar.thumb.border": TRANSPARENT,
    "scrollbar.track.background": TRANSPARENT,
    "scrollbar.track.border": TRANSPARENT,
    "editor.background": sem.bg,
    "editor.foreground": sem.text,
    "editor.gutter.background": sem.bg,
    "editor.subheader.background": sem.surface,
    "editor.line_number": sem["text-faint"],
    "editor.active_line_number": accent.indigo,
    "editor.hover_line_number": sem["text-subtle"],
    "editor.active_line.background": alpha(sem.text, 5),
    "editor.highlighted_line.background": sem.surface,
    "editor.invisible": sem["text-faint"],
    "editor.wrap_guide": alpha(sem.text, 5),
    "editor.active_wrap_guide": alpha(sem.text, 10),
    "editor.indent_guide": alpha(sem.text, 8),
    "editor.indent_guide_active": alpha(sem.text, 22),
    "editor.document_highlight.read_background": alpha(sem.info, 18),
    "editor.document_highlight.write_background": alpha(sem["border-strong"], 40),
    "search.match_background": alpha(sem.info, 30),
    "search.active_match_background": alpha(accent.orange, 40),
    "terminal.background": sem.bg,
    "terminal.foreground": sem.text,
    "terminal.bright_foreground": sem.text,
    "terminal.dim_foreground": sem["text-faint"],
    "terminal.ansi.black": ansi.black,
    "terminal.ansi.bright_black": ansi.brightBlack,
    "terminal.ansi.red": ansi.red,
    "terminal.ansi.bright_red": ansi.brightRed,
    "terminal.ansi.green": ansi.green,
    "terminal.ansi.bright_green": ansi.brightGreen,
    "terminal.ansi.yellow": ansi.yellow,
    "terminal.ansi.bright_yellow": ansi.brightYellow,
    "terminal.ansi.blue": ansi.blue,
    "terminal.ansi.bright_blue": ansi.brightBlue,
    "terminal.ansi.magenta": ansi.magenta,
    "terminal.ansi.bright_magenta": ansi.brightMagenta,
    "terminal.ansi.cyan": ansi.cyan,
    "terminal.ansi.bright_cyan": ansi.brightCyan,
    "terminal.ansi.white": ansi.white,
    "terminal.ansi.bright_white": ansi.brightWhite,
    error: sem.error,
    "error.background": alpha(sem.error, 28),
    "error.border": alpha(sem.error, 65),
    warning: sem.warning,
    "warning.background": alpha(sem.warning, 28),
    "warning.border": alpha(sem.warning, 65),
    success: sem.success,
    "success.background": alpha(sem.success, 28),
    "success.border": alpha(sem.success, 65),
    info: sem.info,
    "info.background": alpha(sem.info, 28),
    "info.border": alpha(sem.info, 65),
    hint: sem.hint,
    "hint.background": alpha(sem.hint, 12),
    "hint.border": alpha(sem.hint, 40),
    predictive: sem["text-faint"],
    "predictive.background": alpha(sem["text-faint"], 12),
    "predictive.border": alpha(sem["text-faint"], 40),
    created: sem.success,
    "created.background": alpha(sem.success, 12),
    "created.border": alpha(sem.success, 40),
    modified: sem.warning,
    "modified.background": alpha(sem.warning, 12),
    "modified.border": alpha(sem.warning, 40),
    deleted: sem.error,
    "deleted.background": alpha(sem.error, 12),
    "deleted.border": alpha(sem.error, 40),
    conflict: accent.orange,
    "conflict.background": alpha(accent.orange, 12),
    "conflict.border": alpha(accent.orange, 40),
    renamed: sem.info,
    "renamed.background": alpha(sem.info, 12),
    "renamed.border": alpha(sem.info, 40),
    hidden: sem["text-faint"],
    "hidden.background": alpha(sem["text-faint"], 12),
    "hidden.border": alpha(sem["text-faint"], 40),
    ignored: sem["text-faint"],
    "ignored.background": alpha(sem["text-faint"], 12),
    "ignored.border": alpha(sem["text-faint"], 40),
    unreachable: sem["text-subtle"],
    "unreachable.background": alpha(sem["text-subtle"], 12),
    "unreachable.border": alpha(sem["text-subtle"], 40),
    "link_text.hover": sem["link-hover"],
    "version_control.added": sem.success,
    "version_control.modified": sem.warning,
    "version_control.deleted": sem.error,
    "version_control.word_added": alpha(sem.success, 35),
    "version_control.word_deleted": alpha(sem.error, 35),
    "version_control.conflict_marker.ours": alpha(sem.success, 12),
    "version_control.conflict_marker.theirs": alpha(sem.link, 12),
    players: [
      {
        cursor: sem.cursor,
        selection: alpha(sem["border-strong"], 30),
        background: sem.cursor,
      },
    ],
    syntax: {
      keyword: { color: syn.keyword },
      string: { color: syn.string },
      "string.escape": { color: syn.escape },
      "string.regex": { color: syn.escape },
      number: { color: syn.number },
      constant: { color: syn.number },
      boolean: { color: syn.number },
      function: { color: syn.function },
      "function.method": { color: syn.function },
      type: { color: syn.type },
      "type.builtin": { color: syn.type },
      constructor: { color: syn.type },
      variable: { color: sem.text },
      "variable.parameter": { color: syn.parameter },
      "variable.special": { color: syn.builtin },
      property: { color: syn.property },
      tag: { color: syn.tag },
      attribute: { color: syn.attribute },
      "constant.builtin": { color: syn.builtin },
      operator: { color: syn.operator },
      punctuation: { color: syn.punctuation },
      "punctuation.bracket": { color: syn.punctuation },
      "punctuation.delimiter": { color: syn.punctuation },
      comment: { color: syn.comment, font_style: "italic" },
      "comment.doc": { color: n.n8 },
      preproc: { color: syn.decorator },
      embedded: { color: sem.text },
      emphasis: { color: accent.blue, font_style: "italic" },
      "emphasis.strong": { color: accent.orange, font_weight: 700 },
      link_uri: { color: sem.link },
      link_text: { color: accent.teal },
      title: { color: accent.yellow, font_weight: 700 },
    },
  };

  const blurStyle = {
    ...baseStyle,
    "background.appearance": "blurred",
    background: alpha(sem["bg-dim"], 84),
    "surface.background": alpha(sem["bg-dim"], 82),
    "title_bar.background": alpha(sem["bg-dim"], 84),
    "status_bar.background": alpha(sem["bg-dim"], 84),
    "tab.inactive_background": TRANSPARENT,
    "tab.active_background": alpha(sem.bg, 38),
    "tab_bar.background": TRANSPARENT,
    "toolbar.background": TRANSPARENT,
    "panel.background": TRANSPARENT,
    "editor.background": TRANSPARENT,
    "editor.gutter.background": TRANSPARENT,
    "terminal.background": TRANSPARENT,
  };

  const theme = {
    $schema: "https://zed.dev/schema/themes/v0.2.0.json",
    name: meta.name,
    author: "Arishawke",
    themes: [
      { name: meta.name, appearance: meta.appearance, style: baseStyle },
      {
        name: `${meta.name} Blur`,
        appearance: meta.appearance,
        style: blurStyle,
      },
    ],
  };

  const content = JSON.stringify(theme, null, 2) + "\n";
  const outputs = [{ path: `ports/zed/${meta.slug}.json`, content }];
  if (meta.appearance !== "light") {
    outputs.push({ path: `themes/${meta.slug}.json`, content });
  }
  return outputs;
}
