# Fadetouched for zsh-syntax-highlighting. Generated from palette.json. Do not edit by hand.
# Source from .zshrc AFTER zsh-syntax-highlighting.zsh.
# Needs zsh >= 5.7 and a truecolor terminal (otherwise: zmodload zsh/nearcolor).

typeset -gA ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[comment]='fg=#666f6b'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#c87a75,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#af90c3'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#af90c3'
ZSH_HIGHLIGHT_STYLES[command]='fg=#7daacf'
ZSH_HIGHLIGHT_STYLES[function]='fg=#7daacf'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#7daacf'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#7daacf'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#c87a75'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#81b8a8'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#81b8a8'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#81b8a8'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#81b8a8'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#96bb93'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#96bb93'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#96bb93'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#96bb93'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#96bb93'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#c593af'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#c593af'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#c593af'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#c87a75'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#c87a75'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#c87a75'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg=#c87a75'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#bc836c'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#bc836c'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#99c9c9'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#99c9c9'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#99c9c9'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#99c9c9'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=#99c9c9'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#d7a176'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#c593af'
ZSH_HIGHLIGHT_STYLES[path]='fg=#b3b7b4,underline'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#b3b7b4,underline'
